In [1]:
import tensorflow as tf

    operate shape(1,) Tensor 
    Building computational graph(Constant)
   

In [2]:
a = tf.constant(3.0, dtype=tf.float32)
b=tf.constant(4.0) # also tf.float32 implicitly

total = a+b
print(a)
print(b)
print(total)


Tensor("Const:0", shape=(), dtype=float32)
Tensor("Const_1:0", shape=(), dtype=float32)
Tensor("add:0", shape=(), dtype=float32)


Running Computational graph

In [3]:
a = tf.constant(3.0, dtype=tf.float32)
b=tf.constant(4.0)
total = a+b

sess = tf.Session()
print(sess.run(total))
print(sess.run([a,b]))
sess.close()

7.0
[3.0, 4.0]


    operate shape(2,) Tensor
    Building computational graph(Constant)

In [4]:
a=tf.constant([3.0,4.0], dtype=tf.float32)
print(a)

Tensor("Const_4:0", shape=(2,), dtype=float32)


Running Computational graph

In [5]:
sess=tf.Session()
print(sess.run(a))
sess.close()

[ 3.  4.]


Builiding computational graph(Placeholder)

In [6]:
x=tf.placeholder(tf.float32)
y=tf.placeholder(tf.float32)

z=x+y

print(x)
print(y)
print(z)

Tensor("Placeholder:0", dtype=float32)
Tensor("Placeholder_1:0", dtype=float32)
Tensor("add_2:0", dtype=float32)


In [7]:
x1=tf.placeholder(tf.float32, shape=[2])
y1 = tf.placeholder(tf.float32, shape=[2])
z1=x1+y1

print(x1)
print(y1)
print(z1)


Tensor("Placeholder_2:0", shape=(2,), dtype=float32)
Tensor("Placeholder_3:0", shape=(2,), dtype=float32)
Tensor("add_3:0", shape=(2,), dtype=float32)


Running Computational graph(Placeholder)

In [8]:
sess=tf.Session()
print(sess.run(z, feed_dict={x:3, y:4.5}))
sess.close()

7.5


In [9]:
sess = tf.Session()
print(sess.run(z1, feed_dict={x1:[1,3], y1:[2,4]}))
sess.close()

[ 3.  7.]


Building computational graph(Variable)

In [10]:
my_variable=tf.Variable("my_variable", [1,2,3])
print(my_variable)

<tf.Variable 'Variable:0' shape=() dtype=string_ref>


In [11]:
my_variable=tf.Variable("my_variable", [1,2,3])
print(my_variable)

<tf.Variable 'Variable_1:0' shape=() dtype=string_ref>


In [12]:
my_variable=tf.Variable("my_variable", [1,2,3])
print(my_variable)

<tf.Variable 'Variable_2:0' shape=() dtype=string_ref>


In [13]:
my_int_variable=tf.get_variable("my_int_variable",[1,2,3], dtype=tf.int32,
                               initializer=tf.zeros_initializer)
print(my_variable)
print(my_int_variable)

<tf.Variable 'Variable_2:0' shape=() dtype=string_ref>
<tf.Variable 'my_int_variable:0' shape=(1, 2, 3) dtype=int32_ref>


In [14]:
#my_variable=tf.get_variable("my_variable",[1])
#dup=tf.get_variable("my_variable",[1])

Running Computational graph

# Initalize methods...

In [15]:
v=tf.get_variable("v2",[1,2,3], dtype=tf.float32)
sess=tf.Session()
sess.run(tf.global_variables_initializer())
print(sess.run(v))

[[[ 0.79081833  0.4825666  -0.55937725]
  [-0.16150635 -0.83726871  0.37137187]]]


In [16]:
vv1 = tf.get_variable("vv1",[1,2,3], dtype=tf.int32,initializer=tf.zeros_initializer)
vv3=tf.get_variable("vv3",[1,2,3], dtype=tf.float32, initializer=tf.constant_initializer(1.0))

sess=tf.Session()
sess.run(tf.global_variables_initializer())
o1, o2 = sess.run([vv1,vv3])

print(o1)
print(o2)

[[[0 0 0]
  [0 0 0]]]
[[[ 1.  1.  1.]
  [ 1.  1.  1.]]]


In [17]:
v3 = tf.get_variable("v3", [1,2,3], dtype=tf.float32, initializer=tf.random_normal_initializer())
v4 = tf.get_variable('v4',[1,2,3], dtype=tf.float32, initializer=tf.random_uniform_initializer())

sess = tf.Session()
sess.run(tf.global_variables_initializer())
o3,o4 = sess.run([v3,v4])
print(o3)
print(o4)

[[[ 0.21197204 -0.54684722  0.17383982]
  [ 1.68821037  0.10551152 -0.83300251]]]
[[[ 0.93715668  0.59141171  0.44310653]
  [ 0.49055314  0.03517902  0.89062572]]]


같은 값을 가져오게 된다.

In [18]:
# "foo"라는 variable scope가 생긴다.
with tf.variable_scope("foo"):
    my_variable = tf.get_variable("my_variable",[1])

with tf.variable_scope("foo", reuse = True): # foo라는 이름이 있으면 reuse
    dup = tf.get_variable("my_variable",[1])

print(my_variable)
print(dup)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(my_variable))
    print(sess.run(dup))

<tf.Variable 'foo/my_variable:0' shape=(1,) dtype=float32_ref>
<tf.Variable 'foo/my_variable:0' shape=(1,) dtype=float32_ref>
[ 0.6196295]
[ 0.6196295]


다른 값을 가져오게된다.

In [19]:
# # "foo"라는 variable scope가 생긴다.
# with tf.variable_scope("foo"):
#     my_variable = tf.get_variable("my_variable",[1])

# with tf.variable_scope("bar"):
#     dup = tf.get_variable("my_variable",[1])

# print(my_variable)
# print(dup)

# with tf.Session() as sess:
#     sess.run(tf.global_variables_initializer())
#     print(sess.run(my_variable))
#     print(sess.run(dup))

### 직선 방정식 y=wx+b

In [20]:
x = tf.placeholder(tf.float32)
w = tf.get_variable("w", initializer=tf.constant([2.]))

b= tf.constant(4.0)
y = x*w + b

print(x,w,b,y)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(y, feed_dict={x:1}))

Tensor("Placeholder_4:0", dtype=float32) <tf.Variable 'w:0' shape=(1,) dtype=float32_ref> Tensor("Const_6:0", shape=(), dtype=float32) Tensor("add_4:0", dtype=float32)
[ 6.]


In [21]:
x= tf.placeholder(tf.float32, shape=[1])
w2= tf.get_variable("w2",shape=[1],initializer=tf.zeros_initializer)

b= tf.constant([4.0])
y = x*w2+ b

print(x,w2,b,y)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(y, feed_dict={x:[1]}))

Tensor("Placeholder_5:0", shape=(1,), dtype=float32) <tf.Variable 'w2:0' shape=(1,) dtype=float32_ref> Tensor("Const_7:0", shape=(1,), dtype=float32) Tensor("add_5:0", shape=(1,), dtype=float32)
[ 4.]
