In [197]:
import tensorflow as tf
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [198]:
tf.__version__

'1.15.0'

In [201]:
data=pd.read_csv("data/sh_process_n_time.csv", encoding="utf-8")
for c in data.columns:
    print(c)

JUDGE
LOT_ID
PANEL_ID
BLACK_RTD_TEMP_GLASS_START
BLACK_RTD_TEMP_GLASS_END
BLACK_RTD_TEMP_WALL_START
BLACK_RTD_TEMP_WALL_MAX
BLACK_RTD_PRES_START
BLACK_RTD_PRES_END
BLACK_RTD_TEMP_GLASS_OUT
BLACK_RTD_TEMP_HOOD_MAX
AG_RTD_TEMP_GLASS_START
AG_RTD_TEMP_GLASS_END
AG_RTD_TEMP_WALL_START
AG_RTD_TEMP_WALL_MAX
AG_RTD_PRES_START
AG_RTD_PRES_END
AG_RTD_TEMP_GLASS_OUT
AG_RTD_TEMP_HOOD_START
AG_EXPOSURE_TEMP_MASK
BUS_DEVELOP_TEMP_OVEN1
BUS_DEVELOP_TEMP_OVEN2
BUS_DEVELOP_TEMP_OVEN3
BUS_DEVELOP_TEMP_TANK1
BUS_DEVELOP_PH_TANK1.1
BUS_DEVELOP_TEMP_TANK2
BUS_DEVELOP_PH_TANK1.2
BUS_DEVELOP_TEMP_TANK3
BUS_DEVELOP_PRES2
BUS_DEVELOP_PRES3
BUS_FIRE_TEMP_HEAT1_CH01
BUS_FIRE_TEMP_HEAT1_CH03
BUS_FIRE_TEMP_HEAT2_CH01
BUS_FIRE_TEMP_HEAT2_CH02
BUS_FIRE_TEMP_HEAT2_CH03
BUS_FIRE_TEMP_KEEP_CH02
BUS_FIRE_TEMP_ANEAL_CH01
BUS_FIRE_TEMP_ANEAL_CH02
BUS_FIRE_TEMP_ANEAL_CH03
DIELEC_FIRE_TEMP_HEAT1_CH01
DIELEC_FIRE_TEMP_HEAT1_CH02
DIELEC_FIRE_TEMP_HEAT1_CH03
DIELEC_FIRE_TEMP_HEAT2_CH01
DIELEC_FIRE_TEMP_HEAT2_CH02
DIELEC_FIRE_

In [202]:
data['JUDGE'].value_counts()

양품    3573
명점     427
Name: JUDGE, dtype: int64

In [203]:
data['JUDGE']=np.where(data['JUDGE']=="명점",1,0)

In [204]:
data['JUDGE'].value_counts()

0    3573
1     427
Name: JUDGE, dtype: int64

In [205]:
data.sample(1)

JUDGE   LOT_ID PANEL_ID  BLACK_RTD_TEMP_GLASS_START  \
1220      1  LOT-162   PNL-01                        44.5   

      BLACK_RTD_TEMP_GLASS_END  BLACK_RTD_TEMP_WALL_START  \
1220                      99.1                       88.5   

      BLACK_RTD_TEMP_WALL_MAX  BLACK_RTD_PRES_START  BLACK_RTD_PRES_END  \
1220                    114.7                 173.8               179.5   

      BLACK_RTD_TEMP_GLASS_OUT  ...  MC_4DIELEC_1FIRE  MC_5MGO  \
1220                      58.1  ...               2호기      2호기   

      MC_6PHOS_1R_1DISPENSER  MC_6PHOS_1R_2DRY  MC_6PHOS_2G_1DISPENSER  \
1220                     2호기               2호기                     2호기   

      MC_6PHOS_2G_2DRY  MC_6PHOS_3B_1DISPENSER  MC_6PHOS_4FIRE  MC_7PASTE  \
1220               2호기                     2호기             2호기        2호기   

      MC_8AGING  
1220        1호기  

[1 rows x 119 columns]

In [206]:
select_cols=['JUDGE','BLACK_RTD_TEMP_GLASS_START',
'BLACK_RTD_TEMP_GLASS_END',
'BLACK_RTD_TEMP_WALL_START',
'BLACK_RTD_TEMP_WALL_MAX',
'BLACK_RTD_PRES_START',
'BLACK_RTD_PRES_END',
'BLACK_RTD_TEMP_GLASS_OUT',
'BLACK_RTD_TEMP_HOOD_MAX',
'AG_RTD_TEMP_GLASS_START',
'AG_RTD_TEMP_GLASS_END',
'AG_RTD_TEMP_WALL_START',
'AG_RTD_TEMP_WALL_MAX',
'AG_RTD_PRES_START',
'AG_RTD_PRES_END',
'AG_RTD_TEMP_GLASS_OUT',
'AG_RTD_TEMP_HOOD_START',
'AG_EXPOSURE_TEMP_MASK',
'BUS_DEVELOP_TEMP_OVEN1',
'BUS_DEVELOP_TEMP_OVEN2',
'BUS_DEVELOP_TEMP_OVEN3',
'BUS_DEVELOP_TEMP_TANK1',
'BUS_DEVELOP_PH_TANK1.1',
'BUS_DEVELOP_TEMP_TANK2',
'BUS_DEVELOP_PH_TANK1.2',
'BUS_DEVELOP_TEMP_TANK3',
'BUS_DEVELOP_PRES2',
'BUS_DEVELOP_PRES3',
'BUS_FIRE_TEMP_HEAT1_CH01',
'BUS_FIRE_TEMP_HEAT1_CH03',
'BUS_FIRE_TEMP_HEAT2_CH01',
'BUS_FIRE_TEMP_HEAT2_CH02',
'BUS_FIRE_TEMP_HEAT2_CH03',
'BUS_FIRE_TEMP_KEEP_CH02',
'BUS_FIRE_TEMP_ANEAL_CH01',
'BUS_FIRE_TEMP_ANEAL_CH02',
'BUS_FIRE_TEMP_ANEAL_CH03',
'DIELEC_FIRE_TEMP_HEAT1_CH01',
'DIELEC_FIRE_TEMP_HEAT1_CH02',
'DIELEC_FIRE_TEMP_HEAT1_CH03',
'DIELEC_FIRE_TEMP_HEAT2_CH01',
'DIELEC_FIRE_TEMP_HEAT2_CH02',
'DIELEC_FIRE_TEMP_HEAT2_CH03',
'DIELEC_FIRE_TEMP_KEEP_CH01',
'DIELEC_FIRE_TEMP_KEEP_CH03',
'DIELEC_FIRE_TEMP_ANEAL_CH01',
'DIELEC_FIRE_TEMP_ANEAL_CH03',
'DIELEC_FIRE_EXHAUST_HEAT1',
'DIELEC_FIRE_EXHAUST_HEAT2',
'DIELEC_FIRE_EXHAUST_HEAT4',
'DIELEC_FIRE_EXHAUST_HEAT5',
'DIELEC_FIRE_EXHAUST_HEAT6',
'DIELEC_FIRE_EXHAUST_HEAT7',
'PHOS_R_DRY_TEMP_GLASS_START',
'PHOS_R_DRY_TEMP_GLASS_END',
'PHOS_R_DRY_TEMP_WALL_START',
'PHOS_R_DRY_TEMP_WALL_MAX',
'PHOS_R_DRY_PRES_START',
'PHOS_R_DRY_PRES_END',
'PHOS_R_DRY_TEMP_GLASS_OUT',
'PHOS_R_DRY_TEMP_HOOD_START',
'PHOS_G_DRY_TEMP_GLASS_START',
'PHOS_G_DRY_TEMP_GLASS_END',
'PHOS_G_DRY_TEMP_WALL_START',
'PHOS_G_DRY_PRES_START',
'PHOS_G_DRY_PRES_END',
'PHOS_G_DRY_TEMP_GLASS_OUT',
'PHOS_G_DRY_TEMP_HOOD_MAX',
'PHOS_FIRE_TEMP_HEAT_CH01',
'PHOS_FIRE_TEMP_HEAT_CH02',
'PHOS_FIRE_TEMP_HEAT_CH03',
'PHOS_FIRE_TEMP_HEAT_CH04',
'PHOS_FIRE_TEMP_KEEP_CH01',
'PHOS_FIRE_TEMP_KEEP_CH02',
'PHOS_FIRE_TEMP_KEEP_CH03',
'PHOS_FIRE_TEMP_KEEP_CH04',
'PHOS_FIRE_TEMP_ANEAL_CH01',
'PHOS_FIRE_TEMP_ANEAL_CH03',
'PHOS_FIRE_TEMP_ANEAL_CH04',
'PHOS_FIRE_EXHAUST_HEAT1',
'PHOS_FIRE_EXHAUST_HEAT2',
'PHOS_FIRE_EXHAUST_HEAT3',
'PHOS_FIRE_EXHAUST_HEAT4']

In [114]:
# data_selcol=data[1"]
# train_data=pd.DataFrame(data_selcol.values.T, data_selcol.columns, data_selcol.index, dtype=object).to_numpy()
# train_data

In [207]:
x_data=train_data[1:]
y_data=train_data[0]

print(len(x_data))
print(len(y_data))


82
4000


In [208]:
x_data=x_data.T
x_data

array([[44.3, 102.3, 88.8, ..., 3973.0, 4432.0, 2506.0],
       [44.6, 101.6, 88.7, ..., 4097.0, 4499.0, 2573.0],
       [45.0, 114.3, 90.3, ..., 3972.0, 4460.0, 2502.0],
       ...,
       [43.8, 106.3, 88.8, ..., 3986.0, 4425.0, 2513.0],
       [43.7, 98.7, 89.6, ..., 3942.0, 4402.0, 2471.0],
       [41.0, 120.0, 88.5, ..., 4005.0, 4436.0, 2474.0]], dtype=object)

In [215]:
np.unique(y_data)

array([0.0, 1.0], dtype=object)

In [216]:
print(x_data.shape)
print(y_data.shape)
print(np.array([y_data]).shape)

(4000, 82)
(4000,)
(1, 4000)


In [217]:
temp = y_data.reshape((4000,1))
temp.shape

(4000, 1)

In [218]:
len(x_data[0])

82

In [219]:
y_data

array([0.0, 0.0, 0.0, ..., 0.0, 1.0, 0.0], dtype=object)

In [220]:
encoder = StandardScaler()
x_data = encoder.fit_transform(x_data)

In [221]:
len(x_data[0])#.shape

82

In [222]:
y_data.shape

(4000,)

In [223]:
x_data

array([[ 0.16438376, -0.97838254, -0.10575875, ..., -1.24814304,
        -0.70802802, -0.99294789],
       [ 0.39080768, -1.10248426, -0.20645739, ...,  0.91067157,
         0.65734615,  0.4940908 ],
       [ 0.69270624,  1.1490756 ,  1.40472087, ..., -1.26555283,
        -0.13742389, -1.08172631],
       ...,
       [-0.21298943, -0.26922983, -0.10575875, ..., -1.0218157 ,
        -0.85067906, -0.83758563],
       [-0.28846407, -1.61661998,  0.69983038, ..., -1.78784669,
        -1.31938959, -1.76975914],
       [-2.32627934,  2.15961821, -0.40785467, ..., -0.69102959,
        -0.62651315, -1.70317532]])

In [224]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 82])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([len(x_data[0]), 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis using sigmoid: tf.div(1., 1. + tf.exp(tf.matmul(X, W)))
hypothesis = tf.sigmoid(tf.matmul(X, W) + b)

# cost/loss function
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) *
                       tf.log(1 - hypothesis))

train = tf.train.GradientDescentOptimizer(learning_rate=0.000000001).minimize(cost)

# Accuracy computation
# True if hypothesis>0.5 else False
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())

    for step in range(10001):
        cost_val, _ = sess.run([cost, train], feed_dict={X: x_data, Y: temp})
        if step % 200 == 0:
            print(step, cost_val)

    # Accuracy report
    h, c, a = sess.run([hypothesis, predicted, accuracy],
                       feed_dict={X: x_data, Y: temp})
    print("\nHypothesis: ", h, "\nCorrect (Y): ", c, "\nAccuracy: ", a)

    # Model test
    y,p = sess.run([hypothesis, predicted],feed_dict={X: x_data})

    #print result
    print("Real y1: 0 Predict p1: ",p[0])
    print("Real y2: 1 Predict p2: ",p[1])


0 nan
200 nan
400 nan
600 nan
800 nan
1000 nan
1200 nan
1400 nan
1600 nan
1800 nan
2000 nan
2200 nan
2400 nan
2600 nan
2800 nan
3000 nan
3200 nan
3400 nan
3600 nan
3800 nan
4000 nan
4200 nan
4400 nan
4600 nan
4800 nan
5000 nan
5200 nan
5400 nan
5600 nan
5800 nan
6000 nan
6200 nan
6400 nan
6600 nan
6800 nan
7000 nan
7200 nan
7400 nan
7600 nan
7800 nan
8000 nan
8200 nan
8400 nan
8600 nan
8800 nan
9000 nan
9200 nan
9400 nan
9600 nan
9800 nan
10000 nan

Hypothesis:  [[nan]
 [nan]
 [nan]
 ...
 [nan]
 [nan]
 [nan]] 
Correct (Y):  [[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]] 
Accuracy:  0.89325
Real y1: 0 Predict p1:  [0.]
Real y2: 1 Predict p2:  [0.]


In [16]:

#train.txt
# #x0 x1 x2 y
# ex) 
# x1를 수업에 참여한 횟수 x2를 공부한 시간
# y값이 1이면 합격 0이면 불합격 이라고 가정한다.  
# xy =np.array([[ 1,   2,   1,   0],
#               [ 1,   3,   2,   0],
#               [ 1,   3,   5,   0],
#               [ 1,   5,   5,   1],
#               [ 1,   7,   5,   1],
#               [ 1,   2,   5,   1]])
xy=np.array([[1,1,1,1,1,1],[2,3,3,5,7,2],[1,2,5,5,5,5],[0,0,0,1,1,1]])

# 원본 파일은 6행 4열이였다, 하지만 numpy 형식 텍스트 읽는것은 열 우선이라서 4행 6열로 가지고 왔다.
#xy = np.loadtxt('train.txt', unpack=True, dtype='float32')
print(xy[0], xy[-1])        # [ 1.  1.  1.  1.  1.  1.] [ 0.  0.  0.  1.  1.  1.]
 
x_data = xy[:-1]            # [1. 1. 1. 1. 1. 1.] [2. 3. 3. 5. 7. 2.] [1. 2. 5. 5. 5. 5.]
y_data = xy[-1]             # [ 0.  0.  0.  1.  1.  1.]
 
X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)
 
# 1행 * 3열 W를 만들고 각 요소를 -1.0~1.0 사이값으로 초기화
W = tf.Variable(tf.random_uniform([1, len(x_data)], -1.0, 1.0))
 
# 행렬 곱셈. W = (1*3) *  X = (3*6)   ->h = 1행*6열 나온 값의 합
#exp()함수는 e 즉, 실수값만 전달하며,  자연상수(a) 안에 e의 a승이 도니다.
h = tf.matmul(W, X)
hypothesis = tf.div(1., 1. + tf.exp(-h))    
 
#cost function
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) * tf.log(1 - hypothesis))
 
#cost값 최소화 하기
rate = tf.Variable(0.1)
optimizer = tf.train.GradientDescentOptimizer(rate)
train = optimizer.minimize(cost)
 
#초기화를 시켜주는 구문 ->텐서플로우 구동하기 전에 그래프에 연결된 모든 변수를 초기화 해야한다.
init = tf.initialize_all_variables()
 
c = tf.exp(1.0)
d = tf.log(10.0)
 
#세션 실행
sess = tf.Session()
sess.run(init)
 
 
# 파이썬 3.x버전부터는 xrange 가 range로 통합되므로써 range를 사용
# 0부터 2000까지 2001번 반복되는 반복문 
# 너무 많은 출력을 피하기 위해서 step별로 계속 진행되다가 20번에 한번씩 출력
for step in range(2001):
    sess.run(train, feed_dict={X: x_data, Y: y_data})
    if step % 20 == 0:
        print(step, sess.run(cost, feed_dict={X: x_data, Y: y_data}), sess.run(W))
 
print('*'*50)
 
# 결과값이 0또는 1로 딱 떨어지는 것이 아니므로, True /False는 기준치 0.5로 판단하게 된다.
#3번 수업 참여하고 2시간 공부했을 가정 ->불합격
print('[1, 3, 2] :', sess.run(hypothesis, feed_dict={X: [[1], [2], [2]]}) > 0.5)
#5번 수업 참여하고 1시간 공부했을 가정 ->불합격
print('[1, 5, 1] :', sess.run(hypothesis, feed_dict={X: [[1], [5], [1]]}) > 0.5)
#7번 수업 참여하고 3시간 공부했을 가정 ->합격
print('[1, 7, 3] :', sess.run(hypothesis, feed_dict={X: [[1], [7], [3]]}) > 0.5)
 
#x_data 값
print('x_data 값 :',x_data)
#y_data값
print('y_data 값 :',y_data)
sess.close()


[1 1 1 1 1 1] [0 0 0 1 1 1]
0 0.71715593 [[-0.8668916   0.5111566   0.16650295]]
20 0.54223496 [[-1.0893205   0.23304178  0.1632748 ]]
40 0.5215861 [[-1.2609359   0.17663494  0.25521746]]
60 0.50667423 [[-1.4232286   0.15728968  0.3107596 ]]
80 0.49417785 [[-1.5768977   0.15531032  0.34802887]]
100 0.48317453 [[-1.7225496   0.1613484   0.37589967]]
120 0.4733256 [[-1.8607719   0.17092521  0.3987303 ]]
140 0.46444857 [[-1.9921268   0.18188307  0.41868627]]
160 0.4564134 [[-2.1171415   0.19318579  0.43686286]]
180 0.4491148 [[-2.2363026   0.20434397  0.4538287 ]]
200 0.4424645 [[-2.3500533   0.21513589  0.4698903 ]]
220 0.43638662 [[-2.4587975   0.22547136  0.48522192]]
240 0.43081608 [[-2.562902    0.23532426  0.49993035]]
260 0.42569682 [[-2.6626992   0.24469906  0.514086  ]]
280 0.42097995 [[-2.758491    0.25361428  0.5277401 ]]
300 0.41662312 [[-2.8505516   0.26209426  0.54093206]]
320 0.4125894 [[-2.93913     0.27016515  0.55369455]]
340 0.40884635 [[-3.0244536   0.2778527   0.56605

In [225]:
import keras
from keras import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [226]:
keras.__version__

'2.3.1'

In [227]:
classifier = Sequential()
#First Hidden Layer
classifier.add(Dense(4, activation='relu', kernel_initializer='random_normal', input_dim=82))
#Second  Hidden Layer
classifier.add(Dense(4, activation='relu', kernel_initializer='random_normal'))
#Output Layer
classifier.add(Dense(1, activation='sigmoid', kernel_initializer='random_normal'))

Instructions for updating:
If using Keras pass *_constraint arguments to layers.


In [228]:
#Compiling the neural network
classifier.compile(optimizer ='adam',loss='binary_crossentropy', metrics =['accuracy'])

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [230]:
x_data

array([[ 0.16438376, -0.97838254, -0.10575875, ..., -1.24814304,
        -0.70802802, -0.99294789],
       [ 0.39080768, -1.10248426, -0.20645739, ...,  0.91067157,
         0.65734615,  0.4940908 ],
       [ 0.69270624,  1.1490756 ,  1.40472087, ..., -1.26555283,
        -0.13742389, -1.08172631],
       ...,
       [-0.21298943, -0.26922983, -0.10575875, ..., -1.0218157 ,
        -0.85067906, -0.83758563],
       [-0.28846407, -1.61661998,  0.69983038, ..., -1.78784669,
        -1.31938959, -1.76975914],
       [-2.32627934,  2.15961821, -0.40785467, ..., -0.69102959,
        -0.62651315, -1.70317532]])

In [250]:
df_train_x, df_test_x, df_train_y, df_test_y = train_test_split(x_data, y_data, test_size=0.3, random_state=1234)
print("train size is {}".format(df_train_x.shape))
print("test size is {}".format(df_test_x.shape))


train size is (2800, 82)
test size is (1200, 82)


In [251]:
#Fitting the data to the training dataset
classifier.fit(df_train_x,df_train_y, batch_size=10, epochs=100)

Epoch 1/100
2800/2800 [==============================] - 1s 233us/step - loss: 0.1252 - accuracy: 0.9575
Epoch 2/100
2800/2800 [==============================] - 1s 181us/step - loss: 0.1244 - accuracy: 0.9575
Epoch 3/100
2800/2800 [==============================] - 0s 176us/step - loss: 0.1249 - accuracy: 0.9546
Epoch 4/100
2800/2800 [==============================] - 1s 185us/step - loss: 0.1244 - accuracy: 0.9579
Epoch 5/100
2800/2800 [==============================] - 1s 208us/step - loss: 0.1235 - accuracy: 0.9575
Epoch 6/100
2800/2800 [==============================] - 1s 212us/step - loss: 0.1230 - accuracy: 0.9568
Epoch 7/100
2800/2800 [==============================] - 1s 202us/step - loss: 0.1224 - accuracy: 0.9582
Epoch 8/100
2800/2800 [==============================] - 1s 199us/step - loss: 0.1225 - accuracy: 0.9582
Epoch 9/100
2800/2800 [==============================] - 1s 189us/step - loss: 0.1242 - accuracy: 0.9546
Epoch 10/100
2800/2800 [==============================]

2800/2800 [==============================] - 1s 182us/step - loss: 0.1126 - accuracy: 0.9593
Epoch 79/100
2800/2800 [==============================] - 1s 217us/step - loss: 0.1133 - accuracy: 0.9593
Epoch 80/100
2800/2800 [==============================] - 1s 200us/step - loss: 0.1130 - accuracy: 0.9593
Epoch 81/100
2800/2800 [==============================] - 1s 215us/step - loss: 0.1121 - accuracy: 0.9596
Epoch 82/100
2800/2800 [==============================] - 1s 201us/step - loss: 0.1126 - accuracy: 0.9596
Epoch 83/100
2800/2800 [==============================] - 1s 210us/step - loss: 0.1121 - accuracy: 0.9586
Epoch 84/100
2800/2800 [==============================] - 1s 213us/step - loss: 0.1122 - accuracy: 0.9600
Epoch 85/100
2800/2800 [==============================] - 1s 208us/step - loss: 0.1134 - accuracy: 0.9611
Epoch 86/100
2800/2800 [==============================] - 1s 212us/step - loss: 0.1129 - accuracy: 0.9596
Epoch 87/100
2800/2800 [==============================] - 1

In [252]:
eval_model = classifier.evaluate(df_train_x, df_train_y)
eval_model

2800/2800 [==============================] - 0s 32us/step


[0.09970754599464791, 0.9642857313156128]

In [253]:
from sklearn.metrics import accuracy_score


In [260]:
np.unique(df_test_y)

array([0.0, 1.0], dtype=object)

In [242]:
df_test_y.shape

(1200,)

In [269]:
df_test_y=df_test_y.reshape((1200,1))


In [256]:
y_pred=classifier.predict(df_test_x)
y_pred =(y_pred>0.5)

In [262]:
y_pred.shape

(1200, 1)

In [268]:
y_pred=np.where(y_pred==False, 0, 1)
y_pred.shape

(1200, 1)

In [272]:
df_test_y.shape

(1200, 1)

In [282]:
print(y_pred)
print(df_test_y.astype(int))

[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]
[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]


In [283]:
accuracy_score(df_test_y.astype(int),  )


0.92

In [278]:

#Now is the moment of truth. we check the accuracy on the test dataset
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(df_test_y.astype(int), y_pred)
print(cm)

[[1041   38]
 [  58   63]]
